import test from "node:test";
import assert from "node:assert/strict";
import db from "../app/db.server.js";
import { AGENT_DEFINITIONS } from "../app/services/ai/agent-prompts.server.js";
import { ensureAiTeam } from "../app/services/ai/agent-registry.server.js";
import { getOpenAiConnectionStatus, runAgentTask } from "../app/services/ai/agent-runner.server.js";
import { decideResult } from "../app/services/ai/approval.server.js";

test("Vier feste Agentenprofile und Vorlagen sind definiert",()=>{assert.equal(AGENT_DEFINITIONS.length,4);assert.ok(AGENT_DEFINITIONS.every(agent=>agent.templates.length===5&&agent.instructions.length>100))});
test("Fehlender API-Schlüssel verhindert keinen stabilen Phase-1-Betrieb",async()=>{assert.equal(typeof getOpenAiConnectionStatus().configured,"boolean");assert.deepEqual(await runAgentTask(),{executed:false,reason:"Die automatische OpenAI-Ausführung ist in Phase 1 deaktiviert."})});
test("Aufgaben, Ergebnisse und Freigaben bleiben nach Shop getrennt",async()=>{const suffix=`${Date.now()}-${Math.random()}`;const shopA=`ai-test-a-${suffix}.myshopify.com`;const shopB=`ai-test-b-${suffix}.myshopify.com`;try{await ensureAiTeam(shopA);await ensureAiTeam(shopB);const [agentA,agentB]=await Promise.all([db.aiAgent.findUnique({where:{shop_slug:{shop:shopA,slug:"marketing"}}}),db.aiAgent.findUnique({where:{shop_slug:{shop:shopB,slug:"marketing"}}})]);const task=await db.aiTask.create({data:{shop:shopA,agentId:agentA.id,title:"Test",prompt:"Nur ein Test"}});const result=await db.aiResult.create({data:{shop:shopA,taskId:task.id,summary:"Entwurf",content:"Nicht veröffentlicht",status:"APPROVAL_REQUIRED"}});await decideResult({shop:shopA,resultId:result.id,decision:"APPROVED",user:"test"});assert.equal(await db.aiTask.count({where:{shop:shopA,agentId:agentA.id}}),1);assert.equal(await db.aiTask.count({where:{shop:shopB,agentId:agentB.id}}),0);await assert.rejects(()=>decideResult({shop:shopB,resultId:result.id,decision:"APPROVED",user:"test"}),/nicht gefunden/);assert.equal((await db.aiResult.findUnique({where:{id:result.id}})).status,"APPROVED")}finally{for(const shop of[shopA,shopB]){await db.aiActivityLog.deleteMany({where:{shop}});await db.aiApproval.deleteMany({where:{shop}});await db.aiResult.deleteMany({where:{shop}});await db.aiTask.deleteMany({where:{shop}});await db.aiAgent.deleteMany({where:{shop}});await db.aiSettings.deleteMany({where:{shop}})}}});
