import { Form, useActionData, useLoaderData } from "react-router";
import { authenticate } from "../shopify.server";
import db from "../db.server";
import { decideResult } from "../services/ai/approval.server";
import { ensureAiTeam } from "../services/ai/agent-registry.server";
import { AiTeamNav, AI_STATUS_LABELS, cardStyle, notice } from "../ai-team";
export const loader=async({request})=>{const{session}=await authenticate.admin(request);await ensureAiTeam(session.shop);return{results:await db.aiResult.findMany({where:{shop:session.shop},include:{task:{include:{agent:true}},approvals:{orderBy:{updatedAt:"desc"},take:1}},orderBy:{createdAt:"desc"}})}};
export const action=async({request})=>{const{session}=await authenticate.admin(request);const form=await request.formData();try{await decideResult({shop:session.shop,resultId:Number(form.get("resultId")),decision:String(form.get("decision")),user:session.email||null,rejectionReason:String(form.get("rejectionReason")||"").trim()||null});return{ok:true,message:"Die Freigabeentscheidung wurde gespeichert. Es wurde nichts veröffentlicht."}}catch(error){return{ok:false,error:String(error?.message||error)}}};
export default function Results(){const{results}=useLoaderData();const data=useActionData();return <s-page heading="KI-Team · Ergebnisse"><AiTeamNav/>{data?.message&&<s-banner tone="success">{data.message}</s-banner>}{data?.error&&<s-banner tone="critical">{data.error}</s-banner>}<s-section>{results.length?results.map(result=><article key={result.id} style={{...cardStyle,marginBottom:12}}><p><strong>{result.task.agent.name}</strong> · {result.task.title} · {AI_STATUS_LABELS[result.status]||result.status}</p><h2>{result.summary}</h2><p style={{whiteSpace:"pre-wrap"}}>{result.content}</p><s-banner tone="warning">{notice}</s-banner><p><strong>Freigabe:</strong> {result.approvals[0]?.status||"PENDING"}</p><div style={{display:"flex",gap:8,flexWrap:"wrap"}}><Form method="post"><input type="hidden" name="resultId" value={result.id}/><input type="hidden" name="decision" value="APPROVED"/><button>Ergebnis freigeben</button></Form><Form method="post" style={{display:"flex",gap:6}}><input type="hidden" name="resultId" value={result.id}/><input type="hidden" name="decision" value="REJECTED"/><input name="rejectionReason" required placeholder="Ablehnungsgrund"/><button>Ergebnis ablehnen</button></Form></div></article>):<p>Noch keine Ergebnisse.</p>}</s-section></s-page>}
