import { Form, useActionData, useLoaderData, useNavigation } from "react-router";
import { authenticate } from "../shopify.server";
import db from "../db.server";
import { getAgent, getDefinition } from "../services/ai/agent-registry.server";
import { AiTeamNav, AI_STATUS_LABELS, cardStyle, gridStyle, notice } from "../ai-team";

const allowedSlugs=new Set(["marketing","seo","social-media","email-marketing"]);
const read=(form,key)=>String(form.get(key)||"").trim();
export const loader=async({request,params})=>{const{session}=await authenticate.admin(request);if(!allowedSlugs.has(params.agentSlug))throw new Response("Agent nicht gefunden",{status:404});const agent=await getAgent(session.shop,params.agentSlug);const tasks=await db.aiTask.findMany({where:{shop:session.shop,agentId:agent.id},include:{results:{orderBy:{createdAt:"desc"},take:1}},orderBy:{createdAt:"desc"},take:20});return{agent:{...agent,goals:JSON.parse(agent.goals)},definition:getDefinition(params.agentSlug),tasks}};
export const action=async({request,params})=>{const{session}=await authenticate.admin(request);const agent=await getAgent(session.shop,params.agentSlug);if(!agent)return{ok:false,error:"Agent nicht gefunden."};const form=await request.formData();const intent=read(form,"intent");try{if(intent==="createTask"){const title=read(form,"title"),prompt=read(form,"prompt");if(!title||!prompt)throw new Error("Titel und Aufgabenbeschreibung sind erforderlich.");const task=await db.aiTask.create({data:{shop:session.shop,agentId:agent.id,title,prompt,context:read(form,"context")||null,status:"DRAFT",priority:Number(form.get("priority")||0),requestedBy:session.email||null}});await db.aiActivityLog.create({data:{shop:session.shop,agentId:agent.id,taskId:task.id,action:"TASK_CREATED",details:title}});return{ok:true,message:"Die Aufgabe wurde als Entwurf gespeichert."}}if(intent==="saveResult"){const taskId=Number(form.get("taskId"));const task=await db.aiTask.findFirst({where:{id:taskId,shop:session.shop,agentId:agent.id}});if(!task)throw new Error("Aufgabe nicht gefunden.");const summary=read(form,"summary"),content=read(form,"content");if(!summary||!content)throw new Error("Zusammenfassung und Ergebnistext sind erforderlich.");const result=await db.aiResult.create({data:{shop:session.shop,taskId,summary,content,status:"APPROVAL_REQUIRED"}});await db.aiApproval.create({data:{shop:session.shop,taskId,resultId:result.id,status:"PENDING",actionType:"CONTENT_REVIEW"}});await db.aiTask.update({where:{id:taskId},data:{status:"APPROVAL_REQUIRED",completedAt:new Date()}});await db.aiActivityLog.create({data:{shop:session.shop,agentId:agent.id,taskId,action:"RESULT_SAVED"}});return{ok:true,message:"Das Ergebnis wurde gespeichert und wartet auf Freigabe."}}throw new Error("Aktion nicht erkannt.")}catch(error){return{ok:false,error:String(error?.message||error)}}};
export default function AgentPage(){const{agent,definition,tasks}=useLoaderData();const actionData=useActionData();const navigation=useNavigation();return <s-page heading={agent.name}><AiTeamNav/>{actionData?.message&&<s-banner tone="success">{actionData.message}</s-banner>}{actionData?.error&&<s-banner tone="critical">{actionData.error}</s-banner>}<s-section><div style={gridStyle}><div style={cardStyle}><h2>Fachgebiet</h2><p>{agent.role}</p><p>{agent.description}</p><strong>Ziele</strong><ul>{agent.goals.map(goal=><li key={goal}>{goal}</li>)}</ul></div><div style={cardStyle}><h2>Feste Arbeitsregeln</h2><p>{agent.instructions}</p><s-banner tone="warning">Keine automatische Veröffentlichung oder externe Aktion.</s-banner></div></div></s-section><s-section heading="Neue Aufgabe erstellen"><Form method="post" style={{display:"grid",gap:12}}><input type="hidden" name="intent" value="createTask"/><label>Titel<input name="title" required style={inputStyle}/></label><label>Aufgabenbeschreibung<textarea name="prompt" required rows="5" style={inputStyle}/></label><label>Zusätzlicher Kontext<textarea name="context" rows="3" style={inputStyle}/></label><label>Priorität<select name="priority" style={inputStyle}><option value="0">Normal</option><option value="1">Hoch</option><option value="2">Dringend</option></select></label><button style={primaryStyle} disabled={navigation.state!=="idle"}>Neue Aufgabe erstellen</button></Form><h3>Vorlagen</h3><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{definition.templates.map(template=><span key={template} style={{padding:"7px 10px",borderRadius:20,background:"#f1f2f3"}}>{template}</span>)}</div></s-section><s-section heading="Letzte Aufgaben">{tasks.length?tasks.map(task=><details key={task.id} style={{...cardStyle,marginBottom:10}}><summary><strong>{task.title}</strong> · {AI_STATUS_LABELS[task.status]||task.status}</summary><p>{task.prompt}</p>{task.results[0]?<div><s-banner tone="info">{notice}</s-banner><h3>{task.results[0].summary}</h3><p style={{whiteSpace:"pre-wrap"}}>{task.results[0].content}</p><s-button href="/app/ki-team/ergebnisse">Ergebnis öffnen</s-button></div>:<Form method="post" style={{display:"grid",gap:8}}><input type="hidden" name="intent" value="saveResult"/><input type="hidden" name="taskId" value={task.id}/><label>Ergebnis-Zusammenfassung<input name="summary" required style={inputStyle}/></label><label>Ergebnisentwurf<textarea name="content" required rows="6" style={inputStyle}/></label><button>Ergebnis als Entwurf speichern</button></Form>}</details>):<p>Noch keine Aufgaben.</p>}</s-section></s-page>}
const inputStyle={display:"block",width:"100%",padding:10,marginTop:5,border:"1px solid #bbb",borderRadius:8};const primaryStyle={padding:"12px 16px",background:"#202223",color:"white",border:0,borderRadius:8,fontWeight:700};
