import { Form, useActionData, useLoaderData } from "react-router";
import { authenticate } from "../shopify.server";
import db from "../db.server";
import { ensureAiTeam } from "../services/ai/agent-registry.server";
import { AiTeamNav, AI_STATUS_LABELS, cardStyle } from "../ai-team";
const read=(form,key)=>String(form.get(key)||"").trim();
export const loader=async({request})=>{const{session}=await authenticate.admin(request);await ensureAiTeam(session.shop);return{tasks:await db.aiTask.findMany({where:{shop:session.shop},include:{agent:true,results:true},orderBy:[{priority:"desc"},{createdAt:"desc"}]})}};
export const action=async({request})=>{const{session}=await authenticate.admin(request);const form=await request.formData();const taskId=Number(form.get("taskId"));const intent=read(form,"intent");const task=await db.aiTask.findFirst({where:{id:taskId,shop:session.shop}});if(!task)return{ok:false,error:"Aufgabe nicht gefunden."};if(intent==="archive")await db.aiTask.update({where:{id:task.id},data:{status:"ARCHIVED"}});else if(intent==="duplicate"){const copy=await db.aiTask.create({data:{shop:session.shop,agentId:task.agentId,title:`${task.title} (Kopie)`,prompt:task.prompt,context:task.context,status:"DRAFT",priority:task.priority,requestedBy:session.email||null}});await db.aiActivityLog.create({data:{shop:session.shop,agentId:copy.agentId,taskId:copy.id,action:"TASK_DUPLICATED"}})}else if(intent==="update"){const title=read(form,"title"),prompt=read(form,"prompt");if(!title||!prompt)return{ok:false,error:"Titel und Beschreibung sind erforderlich."};await db.aiTask.update({where:{id:task.id},data:{title,prompt,context:read(form,"context")||null,priority:Number(form.get("priority")||0),status:read(form,"status")||task.status}})}else return{ok:false,error:"Aktion nicht erkannt."};return{ok:true,message:"Aufgabe wurde aktualisiert."}};
export default function Tasks(){const{tasks}=useLoaderData();const data=useActionData();return <s-page heading="KI-Team · Aufgaben"><AiTeamNav/>{data?.message&&<s-banner tone="success">{data.message}</s-banner>}{data?.error&&<s-banner tone="critical">{data.error}</s-banner>}<s-section>{tasks.length?tasks.map(task=><details key={task.id} style={{...cardStyle,marginBottom:10}}><summary><strong>{task.title}</strong> · {task.agent.name} · {AI_STATUS_LABELS[task.status]||task.status}</summary><Form method="post" style={{display:"grid",gap:8,marginTop:12}}><input type="hidden" name="intent" value="update"/><input type="hidden" name="taskId" value={task.id}/><label>Titel<input name="title" defaultValue={task.title} style={input}/></label><label>Beschreibung<textarea name="prompt" defaultValue={task.prompt} rows="4" style={input}/></label><label>Kontext<textarea name="context" defaultValue={task.context||""} rows="2" style={input}/></label><label>Status<select name="status" defaultValue={task.status} style={input}>{Object.entries(AI_STATUS_LABELS).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Priorität<select name="priority" defaultValue={task.priority} style={input}><option value="0">Normal</option><option value="1">Hoch</option><option value="2">Dringend</option></select></label><button>Aufgabe bearbeiten</button></Form><div style={{display:"flex",gap:8,marginTop:8}}><Form method="post"><input type="hidden" name="intent" value="duplicate"/><input type="hidden" name="taskId" value={task.id}/><button>Aufgabe duplizieren</button></Form><Form method="post"><input type="hidden" name="intent" value="archive"/><input type="hidden" name="taskId" value={task.id}/><button>Archivieren</button></Form>{task.results.length>0&&<s-button href="/app/ki-team/ergebnisse">Ergebnis öffnen</s-button>}</div></details>):<p>Noch keine Aufgaben.</p>}</s-section></s-page>}
const input={display:"block",width:"100%",padding:9,border:"1px solid #bbb",borderRadius:7};
