import { Form, useActionData, useLoaderData } from "react-router";
import { authenticate } from "../shopify.server";
import db from "../db.server";
import { ensureAiTeam } from "../services/ai/agent-registry.server";
import { getOpenAiConnectionStatus } from "../services/ai/agent-runner.server";
import { getUsageSummary } from "../services/ai/usage.server";
import { AiTeamNav, cardStyle } from "../ai-team";
export const loader=async({request})=>{const{session}=await authenticate.admin(request);await ensureAiTeam(session.shop);const[settings,agents,usage]=await Promise.all([db.aiSettings.findUnique({where:{shop:session.shop}}),db.aiAgent.findMany({where:{shop:session.shop},orderBy:{id:"asc"}}),getUsageSummary(session.shop)]);return{settings,agents,usage,connection:getOpenAiConnectionStatus()}};
export const action=async({request})=>{const{session}=await authenticate.admin(request);await ensureAiTeam(session.shop);const form=await request.formData();const max=Math.max(1,Math.min(Number(form.get("maxTasksPerDay")||10),100));await db.$transaction(async tx=>{await tx.aiSettings.update({where:{shop:session.shop},data:{approvalRequired:form.get("approvalRequired")==="on",maxTasksPerDay:max,usageLimitCents:Math.max(0,Math.round(Number(form.get("usageLimit")||0)*100)),loggingEnabled:form.get("loggingEnabled")==="on",autoRunEnabled:false}});const agents=await tx.aiAgent.findMany({where:{shop:session.shop}});for(const agent of agents)await tx.aiAgent.update({where:{id:agent.id},data:{active:form.get(`agent-${agent.id}`)==="on"}})});return{ok:true,message:"Einstellungen gespeichert. Automatisches Ausführen bleibt deaktiviert."}};
export default function Settings(){const{settings,agents,usage,connection}=useLoaderData();const data=useActionData();return <s-page heading="KI-Team · Einstellungen"><AiTeamNav/>{data?.message&&<s-banner tone="success">{data.message}</s-banner>}<s-section><div style={cardStyle}><p><strong>OpenAI-Verbindung:</strong> {connection.configured?"Eingerichtet":"Nicht eingerichtet"}</p>{!connection.configured&&<s-banner tone="info">Die OpenAI-Verbindung ist noch nicht eingerichtet.</s-banner>}<p>Heute erstellte Aufgaben: {usage.tasksToday} · Erfasste Tokens: {usage.tokenUsage} · Geschätzte Nutzung: {usage.estimatedCost.toLocaleString("de-DE",{style:"currency",currency:"EUR"})}</p></div><Form method="post" style={{...cardStyle,marginTop:12,display:"grid",gap:10}}><h2>Agenten</h2>{agents.map(agent=><label key={agent.id}><input type="checkbox" name={`agent-${agent.id}`} defaultChecked={agent.active}/> {agent.name} aktiv</label>)}<h2>Sicherheit und Limits</h2><label><input type="checkbox" name="approvalRequired" defaultChecked={settings.approvalRequired}/> Standardmäßige Freigabepflicht</label><label><input type="checkbox" name="loggingEnabled" defaultChecked={settings.loggingEnabled}/> Protokollierung aktiv</label><label><input type="checkbox" checked={false} readOnly/> Automatisches Ausführen (in Phase 1 deaktiviert)</label><label>Maximale Aufgaben pro Tag<input type="number" name="maxTasksPerDay" min="1" max="100" defaultValue={settings.maxTasksPerDay}/></label><label>Geschätztes Nutzungslimit in Euro<input type="number" name="usageLimit" min="0" step="0.01" defaultValue={(settings.usageLimitCents/100).toFixed(2)}/></label><button>Einstellungen speichern</button></Form></s-section></s-page>}
